# Generated by Django 4.2.2 on 2023-06-11 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50)),
                ('father_name', models.CharField(max_length=64, null=True)),
                ('mother_name', models.CharField(max_length=64, null=True)),
                ('standard', models.CharField(max_length=10, null=True)),
                ('roll_number', models.BigIntegerField(default=0, null=True)),
                ('telephone', models.BigIntegerField(default=0, null=True)),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('residence', models.TextField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('profile_pic', models.ImageField(default='', upload_to='')),
                ('birthday', models.DateField(null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('physics_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('mathematics_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('mathematics_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('chemistry_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('chemistry_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('biology_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('biology_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('computer_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('computer_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('hindi_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('hindi_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('english_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('english_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('history_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('history_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('geography_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('geography_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('sanskrit_exam_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('sanskrit_assingment_marks', models.FloatField(default=0, max_length=64, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsite.student')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_thought', models.CharField(default='', max_length=800, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsite.student')),
                ('teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cocurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(blank=True, choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Race', 'Race'), ('Kabaddi', 'Kabaddi'), ('Tennis', 'Tennis')], max_length=64)),
                ('singing', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10)),
                ('dancing', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10)),
                ('drawing', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10)),
                ('essays', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10)),
                ('presents', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsite.student')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_achievements', models.ImageField(default='', upload_to='')),
                ('additional_achievements', models.ImageField(default='', upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsite.student')),
            ],
        ),
    ]
