# Generated by Django 4.2.15 on 2024-09-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='computer_assingment_marks',
        ),
        migrations.RemoveField(
            model_name='score',
            name='computer_exam_marks',
        ),
        migrations.RemoveField(
            model_name='score',
            name='geography_assingment_marks',
        ),
        migrations.RemoveField(
            model_name='score',
            name='geography_exam_marks',
        ),
        migrations.RemoveField(
            model_name='score',
            name='history_assingment_marks',
        ),
        migrations.RemoveField(
            model_name='score',
            name='history_exam_marks',
        ),
    ]
