# Generated by Django 4.2.15 on 2024-10-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0002_remove_score_computer_assingment_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
